language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source -n --no-dev
  - composer require spomky-labs/jose:2.0.x-dev

script: phpunit -c phpunit.travis.xml
